### ISSUE TITLE
[帮助]是否有详细的使用文档？

### ISSUE THREAD

**Issue by Cloud33** [wxzz/CSharpFlink#1]
我如何开始，如何使用它？是否能提供更详细的文档。

**Comment by wxzz** [comment]
http://www.cnblogs.com/lsjwq



---原始邮件---
发件人: "Jack Feng"<notifications@github.com&gt;
发送时间: 2020年11月26日(周四) 下午5:04
收件人: "wxzz/CSharpFlink"<CSharpFlink@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [wxzz/CSharpFlink] [帮助]是否有详细的使用文档？ (#1)




 
我如果使用它？是否能提供更详细的文档。

**Comment by Cloud33** [comment]
我还是不知道，如何开始？希望能有一段文章讲一下，谢谢

**Comment by wxzz** [comment]
有文档，有代码demo



---原始邮件---
发件人: "Jack Feng"<notifications@github.com&gt;
发送时间: 2020年11月26日(周四) 下午5:09
收件人: "wxzz/CSharpFlink"<CSharpFlink@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"wxzz"<504547114@qq.com&gt;;
主题: Re: [wxzz/CSharpFlink] [帮助]是否有详细的使用文档？ (#1)




 
我还是不知道，如何开始？希望能有一段文章讲一下，谢谢

**Comment by Cloud33** [comment]
好，我看看test里面的东西，了解一下，谢谢
