### ISSUE TITLE
[帮助]提供全部一点的Demo

### ISSUE THREAD

**Issue by Cloud33** [wxzz/CSharpFlink#3]
项目下的`test->TestTask`示例太简单的，有没有使用`CSharpFlink`全功能的Demo？这样更好的帮助大家使用`CSharpFlink`

**Comment by wxzz** [comment]
我们没有办法把所有应用场景都写了DEMO。其实源代码在那，您还是要看一下。包括框架图也有。这样更有利于您灵活掌握。我们现在的应用场景是：窗口时间范围内的聚合计算、实时预警、多数据点复杂表达式的计算等。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jack Feng"<notifications@github.com&gt;; 
发送时间: 2020年12月9日(星期三) 上午9:49
收件人: "wxzz/CSharpFlink"<CSharpFlink@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [wxzz/CSharpFlink] [帮助]提供全部一点的Demo (#3)





 
项目下的test-&gt;TestTask示例太简单的，有没有使用CSharpFlink全功能的Demo？这样更好的帮助大家使用CSharpFlink

**Comment by Cloud33** [comment]
好的，`CSharpFlink`非常有价值，希望有很多的创新。
